name: lulu
version: 0.1.0.0
github: "jasonliang512/lulu"
license: BSD3
author: "Jason Liang"
maintainer: "jasonliang512.com"
copyright: "2020 Jason Liang"

extra-source-files:
  - README.md
  - ChangeLog.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/jasonliang512/lulu#readme>

dependencies:
  - base

library:
  source-dirs: src
  dependencies:
    - raw-strings-qq

executables:
  lulu-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lulu

tests:
  lulu-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - lulu
